version: "2"
services:
  mongo:
    image: mongo
  web:
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=mongo
    command: node server/app.js
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      - mongo